### ISSUE TITLE
Enable Travis CI for the columbia-irt/rtptools repository

### ISSUE THREAD

**Issue by njh** [columbia-irt/rtptools#103]
Travis CI doesn't seem to have been enabled for the columbia-irt/rtptools repository, these are still both 404:
* https://travis-ci.org/columbia-irt/rtptools
* https://travis-ci.org/columbia-irt

travis-ci.**org** is for public repos and mirrors the Github URL structure.

This is the Travis CI build for my own fork of the repo (https://github.com/njh/rtptools):
https://travis-ci.org/njh/rtptools

There is a Getting Started guide here:
https://docs.travis-ci.com/user/getting-started/

Also check that Travis CI has been activated as a Github integration:
https://github.com/columbia-irt/rtptools/settings/installations

**Comment by janakj** [comment]
I activated the repository on travis-ci.org. It should start building after the next push (hopefully). Thanks for the links!

**Comment by mcd500** [comment]
Hi @njh 
Do you mind checking if this is how it should been working?
https://travis-ci.org/columbia-irt/rtptools

**Comment by mcd500** [comment]
Ugh, I pressed the wrong button, I did not meant to reopen it, close it again.

**Comment by njh** [comment]
Looking good! 👍
