### ISSUE TITLE
Don't require GNU make

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#13]
Commit https://github.com/columbia-irt/rtptools/commit/d238467ecea1e2ba3f42b52fe5936bc6e6f41fda introduces

```
$(html_DATA): $(man_MANS)
	groff -Thtml -mdoc $< > $@
```

which generates the html manpages (to put on the web)
from the real manpages, but the syntax is GNU specific.
The resulting Makefile cannot be compiled with standard make(1),
which up to now was possible; GNU make is needed for this.

```
Using $< in a non-suffix rule context is a GNUmake idiom.
```

That one line creates a needless dependency.

**Comment by mcd500** [comment]
This should fix the dependency on GNU make.
https://github.com/columbia-irt/rtptools/commit/69a3f25c7987d0dacb802c5ed17be8af9f868fd1

**Comment by janstary** [comment]
Yes it does, thanks.
