### ISSUE TITLE
ac_fn_c_try_link: command not found

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#20]
`configure` complains while checking for `gethostbyname()`:

```
checking for gethostbyname... ./configure: line 1589: ac_fn_c_try_link: command not found
```

**Comment by mcd500** [comment]
I see this message from the beginning but not critical for fixing it on building the project. It will be nice to have no warning, so pending it for the future at the moment.

**Comment by mcd500** [comment]
This commit should fix this message from ./configure.
Please confirm.
https://github.com/columbia-irt/rtptools/commit/483d215d79c9d43ad1cf46d9cf5a7fabe885c0a6

**Comment by janstary** [comment]
Yes, this fixes it, thanks.
