### ISSUE TITLE
separate the generation of html pages

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#22]
Currently, the rtp*.html pages are generated as a part of normal build (`make`).
But the local user never needs those. Make it a separate build target (`make html`).

**Comment by mcd500** [comment]
Please see the comments here.
https://github.com/columbia-irt/rtptools/commit/b7784758d045223f6d2e009bf5d9b2975551ccc2#commitcomment-26983664

**Comment by mcd500** [comment]
Committed to separated generating html files from man pages.
It is `make html`

https://github.com/columbia-irt/rtptools/commit/16588d2f97305d490b2dfa50fc49836a688447d4
