### ISSUE TITLE
rtptools does not compile on Solaris

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#23]
This is curent git on SunOS 5.11 11.3 sun4v sparc.

$ uname -a
SunOS fray1 5.11 11.3 sun4v sparc SUNW,SPARC-Enterprise-T5120 Solaris

$ ./configure  --prefix=$HOME --mandir=$HOME/man
checking for a BSD-compatible install... /opt/sfw/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking build system type... sparc-sun-solaris2.11
checking host system type... sparc-sun-solaris2.11
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /opt/sfw/bin/install -c
checking for groff... yes
checking for mandoc... yes
checking for man2html... no
checking for egrep... egrep
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking search.h usability... yes
checking search.h presence... yes
checking for search.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for stdint.h... (cached) yes
checking rpcsvc/ypclnt.h usability... yes
checking rpcsvc/ypclnt.h presence... yes
checking for rpcsvc/ypclnt.h... yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... yes
checking for uid_t in sys/types.h... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
./configure[4531]: AC_TYPE_UINT16_T: not found [No such file or directory]
checking whether time.h and sys/time.h may both be included... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking whether gcc needs -traditional... no
checking return type of signal handlers... void
checking for strftime... yes
checking for vprintf... yes
checking for _doprnt... yes
checking for gethostbyname... no
checking for gettimeofday... yes
checking for mktime... yes
checking for select... yes
checking for strdup... yes
checking for strerror... yes
checking for strstr... yes
checking for strtol... yes
checking for uname... yes
checking for gethostbyname... (cached) no
checking for gethostbyname in -lnsl... yes
checking for yp_match... yes
checking for socket... no
checking for socket in -lsocket... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands

$ make
if gcc -DPACKAGE_NAME=\"rtptools\" -DPACKAGE_TARNAME=\"rtptools\" -DPACKAGE_VERSION=\"1.22\" -DPACKAGE_STRING=\"rtptools\ 1.22\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"rtptools\" -DVERSION=\"1.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SEARCH_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDINT_H=1 -DHAVE_YP=1 -DWORDS_BIGENDIAN=1 -DTIME_WITH_SYS_TIME=1 -DRETSIGTYPE=void -DHAVE_STRFTIME=1 -DHAVE_VPRINTF=1 -DHAVE_DOPRNT=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MKTIME=1 -DHAVE_SELECT=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_UNAME=1 -DHAVE_LIBNSL=1 -DHAVE_YP_MATCH=1 -DHAVE_LIBSOCKET=1 -I. -I.      -g -O2 -Wall -MT host2ip.o -MD -MP -MF ".deps/host2ip.Tpo" -c -o host2ip.o host2ip.c; \
then mv -f ".deps/host2ip.Tpo" ".deps/host2ip.Po"; else rm -f ".deps/host2ip.Tpo"; exit 1; fi
if gcc -DPACKAGE_NAME=\"rtptools\" -DPACKAGE_TARNAME=\"rtptools\" -DPACKAGE_VERSION=\"1.22\" -DPACKAGE_STRING=\"rtptools\ 1.22\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"rtptools\" -DVERSION=\"1.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SEARCH_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDINT_H=1 -DHAVE_YP=1 -DWORDS_BIGENDIAN=1 -DTIME_WITH_SYS_TIME=1 -DRETSIGTYPE=void -DHAVE_STRFTIME=1 -DHAVE_VPRINTF=1 -DHAVE_DOPRNT=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MKTIME=1 -DHAVE_SELECT=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_UNAME=1 -DHAVE_LIBNSL=1 -DHAVE_YP_MATCH=1 -DHAVE_LIBSOCKET=1 -I. -I.      -g -O2 -Wall -MT hpt.o -MD -MP -MF ".deps/hpt.Tpo" -c -o hpt.o hpt.c; \
then mv -f ".deps/hpt.Tpo" ".deps/hpt.Po"; else rm -f ".deps/hpt.Tpo"; exit 1; fi
if gcc -DPACKAGE_NAME=\"rtptools\" -DPACKAGE_TARNAME=\"rtptools\" -DPACKAGE_VERSION=\"1.22\" -DPACKAGE_STRING=\"rtptools\ 1.22\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"rtptools\" -DVERSION=\"1.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SEARCH_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDINT_H=1 -DHAVE_YP=1 -DWORDS_BIGENDIAN=1 -DTIME_WITH_SYS_TIME=1 -DRETSIGTYPE=void -DHAVE_STRFTIME=1 -DHAVE_VPRINTF=1 -DHAVE_DOPRNT=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MKTIME=1 -DHAVE_SELECT=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_UNAME=1 -DHAVE_LIBNSL=1 -DHAVE_YP_MATCH=1 -DHAVE_LIBSOCKET=1 -I. -I.      -g -O2 -Wall -MT multimer.o -MD -MP -MF ".deps/multimer.Tpo" -c -o multimer.o multimer.c; \
then mv -f ".deps/multimer.Tpo" ".deps/multimer.Po"; else rm -f ".deps/multimer.Tpo"; exit 1; fi
if gcc -DPACKAGE_NAME=\"rtptools\" -DPACKAGE_TARNAME=\"rtptools\" -DPACKAGE_VERSION=\"1.22\" -DPACKAGE_STRING=\"rtptools\ 1.22\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"rtptools\" -DVERSION=\"1.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SEARCH_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDINT_H=1 -DHAVE_YP=1 -DWORDS_BIGENDIAN=1 -DTIME_WITH_SYS_TIME=1 -DRETSIGTYPE=void -DHAVE_STRFTIME=1 -DHAVE_VPRINTF=1 -DHAVE_DOPRNT=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MKTIME=1 -DHAVE_SELECT=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_UNAME=1 -DHAVE_LIBNSL=1 -DHAVE_YP_MATCH=1 -DHAVE_LIBSOCKET=1 -I. -I.      -g -O2 -Wall -MT notify.o -MD -MP -MF ".deps/notify.Tpo" -c -o notify.o notify.c; \
then mv -f ".deps/notify.Tpo" ".deps/notify.Po"; else rm -f ".deps/notify.Tpo"; exit 1; fi
if gcc -DPACKAGE_NAME=\"rtptools\" -DPACKAGE_TARNAME=\"rtptools\" -DPACKAGE_VERSION=\"1.22\" -DPACKAGE_STRING=\"rtptools\ 1.22\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"rtptools\" -DVERSION=\"1.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SEARCH_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDINT_H=1 -DHAVE_YP=1 -DWORDS_BIGENDIAN=1 -DTIME_WITH_SYS_TIME=1 -DRETSIGTYPE=void -DHAVE_STRFTIME=1 -DHAVE_VPRINTF=1 -DHAVE_DOPRNT=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MKTIME=1 -DHAVE_SELECT=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_UNAME=1 -DHAVE_LIBNSL=1 -DHAVE_YP_MATCH=1 -DHAVE_LIBSOCKET=1 -I. -I.      -g -O2 -Wall -MT rd.o -MD -MP -MF ".deps/rd.Tpo" -c -o rd.o rd.c; \
then mv -f ".deps/rd.Tpo" ".deps/rd.Po"; else rm -f ".deps/rd.Tpo"; exit 1; fi
if gcc -DPACKAGE_NAME=\"rtptools\" -DPACKAGE_TARNAME=\"rtptools\" -DPACKAGE_VERSION=\"1.22\" -DPACKAGE_STRING=\"rtptools\ 1.22\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"rtptools\" -DVERSION=\"1.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SEARCH_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDINT_H=1 -DHAVE_YP=1 -DWORDS_BIGENDIAN=1 -DTIME_WITH_SYS_TIME=1 -DRETSIGTYPE=void -DHAVE_STRFTIME=1 -DHAVE_VPRINTF=1 -DHAVE_DOPRNT=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MKTIME=1 -DHAVE_SELECT=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_UNAME=1 -DHAVE_LIBNSL=1 -DHAVE_YP_MATCH=1 -DHAVE_LIBSOCKET=1 -I. -I.      -g -O2 -Wall -MT rtpdump.o -MD -MP -MF ".deps/rtpdump.Tpo" -c -o rtpdump.o rtpdump.c; \
then mv -f ".deps/rtpdump.Tpo" ".deps/rtpdump.Po"; else rm -f ".deps/rtpdump.Tpo"; exit 1; fi
rtpdump.c: In function â€˜parse_dataâ€™:
rtpdump.c:290:7: warning: format â€˜%lxâ€™ expects argument of type â€˜long unsigned intâ€™, but argument 4 has type â€˜uint32_tâ€™ [-Wformat=]
       fprintf(out, "csrc[%d]=0x%0lx ", i, r->csrc[i]);
       ^
rtpdump.c: In function â€˜mainâ€™:
rtpdump.c:845:24: warning: pointer targets in passing argument 6 of â€˜recvfromâ€™ differ in signedness [-Wpointer-sign]
	     0, (struct sockaddr *)&sin, &alen);
			^
In file included from rtpdump.c:32:0:
/usr/include/sys/socket.h:522:16: note: expected â€˜Psocklen_tâ€™ but argument is of type â€˜int *â€™
 extern ssize_t recvfrom(int, void *_RESTRICT_KYWD, size_t, int,
		^
gcc  -g -O2 -Wall   -o rtpdump	host2ip.o hpt.o multimer.o  notify.o rd.o rtpdump.o  -lsocket -lnsl
if gcc -DPACKAGE_NAME=\"rtptools\" -DPACKAGE_TARNAME=\"rtptools\" -DPACKAGE_VERSION=\"1.22\" -DPACKAGE_STRING=\"rtptools\ 1.22\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"rtptools\" -DVERSION=\"1.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SEARCH_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDINT_H=1 -DHAVE_YP=1 -DWORDS_BIGENDIAN=1 -DTIME_WITH_SYS_TIME=1 -DRETSIGTYPE=void -DHAVE_STRFTIME=1 -DHAVE_VPRINTF=1 -DHAVE_DOPRNT=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MKTIME=1 -DHAVE_SELECT=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_UNAME=1 -DHAVE_LIBNSL=1 -DHAVE_YP_MATCH=1 -DHAVE_LIBSOCKET=1 -I. -I.      -g -O2 -Wall -MT rtpplay.o -MD -MP -MF ".deps/rtpplay.Tpo" -c -o rtpplay.o rtpplay.c; \
then mv -f ".deps/rtpplay.Tpo" ".deps/rtpplay.Po"; else rm -f ".deps/rtpplay.Tpo"; exit 1; fi
rtpplay.c: In function â€˜play_handlerâ€™:
rtpplay.c:155:12: warning: variable â€˜mâ€™ set but not used [-Wunused-but-set-variable]
   uint8_t  m	= 0;
	    ^
rtpplay.c:154:12: warning: variable â€˜seqâ€™ set but not used [-Wunused-but-set-variable]
   uint16_t seq = 0;
	    ^
rtpplay.c: In function â€˜mainâ€™:
rtpplay.c:354:35: warning: pointer targets in passing argument 3 of â€˜hptâ€™ differ in signedness [-Wpointer-sign]
     if (hpt(argv[optind], (struct sockaddr *)&sin, &ttl) < 0) {
				   ^
rtpplay.c:310:14: note: expected â€˜unsigned char *â€™ but argument is of type â€˜char *â€™
   extern int hpt(char *h, struct sockaddr *sa, unsigned char *ttl);
	      ^
gcc  -g -O2 -Wall   -o rtpplay	host2ip.o hpt.o multimer.o  notify.o rd.o  rtpplay.o  -lsocket -lnsl
if gcc -DPACKAGE_NAME=\"rtptools\" -DPACKAGE_TARNAME=\"rtptools\" -DPACKAGE_VERSION=\"1.22\" -DPACKAGE_STRING=\"rtptools\ 1.22\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"rtptools\" -DVERSION=\"1.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SEARCH_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDINT_H=1 -DHAVE_YP=1 -DWORDS_BIGENDIAN=1 -DTIME_WITH_SYS_TIME=1 -DRETSIGTYPE=void -DHAVE_STRFTIME=1 -DHAVE_VPRINTF=1 -DHAVE_DOPRNT=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MKTIME=1 -DHAVE_SELECT=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_UNAME=1 -DHAVE_LIBNSL=1 -DHAVE_YP_MATCH=1 -DHAVE_LIBSOCKET=1 -I. -I.      -g -O2 -Wall -MT rtpsend.o -MD -MP -MF ".deps/rtpsend.Tpo" -c -o rtpsend.o rtpsend.c; \
then mv -f ".deps/rtpsend.Tpo" ".deps/rtpsend.Po"; else rm -f ".deps/rtpsend.Tpo"; exit 1; fi
rtpsend.c: In function â€˜rtpâ€™:
rtpsend.c:716:11: warning: variable â€˜dummyâ€™ set but not used [-Wunused-but-set-variable]
       int dummy;
	   ^
rtpsend.c:658:7: warning: variable â€˜padâ€™ set but not used [-Wunused-but-set-variable]
   int pad = 0;
       ^
rtpsend.c: In function â€˜mainâ€™:
rtpsend.c:918:35: warning: pointer targets in passing argument 3 of â€˜hptâ€™ differ in signedness [-Wpointer-sign]
     if (hpt(argv[optind], (struct sockaddr *)&sin, &ttl) < 0) {
				   ^
rtpsend.c:877:14: note: expected â€˜unsigned char *â€™ but argument is of type â€˜char *â€™
   extern int hpt(char *h, struct sockaddr *sa, unsigned char *ttl);
	      ^
gcc  -g -O2 -Wall   -o rtpsend	host2ip.o hpt.o multimer.o  notify.o rtpsend.o	-lsocket -lnsl
if gcc -DPACKAGE_NAME=\"rtptools\" -DPACKAGE_TARNAME=\"rtptools\" -DPACKAGE_VERSION=\"1.22\" -DPACKAGE_STRING=\"rtptools\ 1.22\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"rtptools\" -DVERSION=\"1.22\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SEARCH_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDINT_H=1 -DHAVE_YP=1 -DWORDS_BIGENDIAN=1 -DTIME_WITH_SYS_TIME=1 -DRETSIGTYPE=void -DHAVE_STRFTIME=1 -DHAVE_VPRINTF=1 -DHAVE_DOPRNT=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MKTIME=1 -DHAVE_SELECT=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_UNAME=1 -DHAVE_LIBNSL=1 -DHAVE_YP_MATCH=1 -DHAVE_LIBSOCKET=1 -I. -I.      -g -O2 -Wall -MT rtptrans.o -MD -MP -MF ".deps/rtptrans.Tpo" -c -o rtptrans.o rtptrans.c; \
then mv -f ".deps/rtptrans.Tpo" ".deps/rtptrans.Po"; else rm -f ".deps/rtptrans.Tpo"; exit 1; fi
rtptrans.c: In function â€˜socket_handlerâ€™:
rtptrans.c:203:17: warning: pointer targets in passing argument 6 of â€˜recvfromâ€™ differ in signedness [-Wpointer-sign]
	 (struct sockaddr *)&sin_from, &addr_len);
		 ^
In file included from rtptrans.c:33:0:
/usr/include/sys/socket.h:522:16: note: expected â€˜Psocklen_tâ€™ but argument is of type â€˜int *â€™
 extern ssize_t recvfrom(int, void *_RESTRICT_KYWD, size_t, int,
		^
rtptrans.c:314:14: error: â€˜struct msghdrâ€™ has no member named â€˜msg_controlâ€™
	   msg.msg_control = 0;
	      ^
rtptrans.c:315:14: error: â€˜struct msghdrâ€™ has no member named â€˜msg_controllenâ€™
	   msg.msg_controllen = 0;
	      ^
rtptrans.c:327:23: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     else if (((struct CtrlMsgHdr *)packet)->type == 1) /* vat ID messages */{
		       ^
*** Error code 1
make: Fatal error: Command failed for target `rtptrans.o'

**Comment by mcd500** [comment]
I do not have access to Solaris machine.
Would you mind checking if changing following line in rtptrans.c at line 313 as bellow would make it compile?

#if !defined(__SVR4) || defined(__unix__) || defined(__FreeBSD__) || defined(__linux__) || defined(__darwin__) /* Or presumably other BSD 4.4 systems */

Currently it is:
#if defined(__unix__) || defined(__FreeBSD__) || defined(__linux__) || defined(__darwin__) /* Or presumably other BSD 4.4 systems */

**Comment by janstary** [comment]
That results in the same error.

**Comment by mcd500** [comment]
It clearly states that it is SunOS and not Solaris in your error messages.
Would you mind trying 
!defined(__sun)
instead of
!defined(__SVR4)?

I was referring here, 
https://sourceforge.net/p/predef/wiki/OperatingSystems/

**Comment by janstary** [comment]
Solaris is SunOS ( https://en.wikipedia.org/wiki/Solaris_(operating_system) ).
Same error with `__sun` in that place.

**Comment by janstary** [comment]
Fixed in https://github.com/columbia-irt/rtptools/pull/31

Solaris (SunOS) also defines `__unix__` like all others, so that's not the distinction.
The distinction seems to be `__sun` alone (thanks for the pointer).

**Comment by mcd500** [comment]
Thanks for the
https://github.com/columbia-irt/rtptools/pull/31
