### ISSUE TITLE
use standard integer type names

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#3]
This is how rtptools curently names the various integer types, in `types.h`:

```
/* 32 bit machines */
#if ULONG_MAX == MAX32U
typedef short int16;
typedef int   int32;
typedef unsigned long  u_int32;
typedef unsigned short u_int16;
```

etc for the other sizes. Isn't that completely backwards?

"If we happen to be on a 32bit machine, short is 16bits,
so lets name short `int16` (sic) and call it that".

If we need 16bit integers, why not just call them the standard `int16_t`
and be done with it, regardless of what machine this is?

**Comment by mcd500** [comment]
Agreed, we should use followings which were added in <stdint.h> from c99.
int16_t
int32_t
int64_t
uint16_t
uint32_t
uint64_t
