### ISSUE TITLE
gcc preferred over cc

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#33]
This is current git on OpenBSD current/amd64.
The system comes with the following compilers:
```
-r-xr-xr-x  6 root  bin  42331608 Mar 17 18:38 /usr/bin/cc
-r-xr-xr-x  6 root  bin  42331608 Mar 17 18:38 /usr/bin/clang
-r-xr-xr-x  1 root  bin    200872 Mar 17 18:38 /usr/bin/gcc
```

That is, `cc` is a hardlink to `clang` (5.0.1), and `gcc` is gcc (4.2.1).
Without specifying a compiler with `./configure ... CC=...`, it seems
that gcc is picked up by default.

Is that intentional? Why?

**Comment by mcd500** [comment]
clang would be nice. Probably the default ac_fn_c_try_compile is failing to detect clang properly.
Let me try adding a work around in configure.ac.

**Comment by mcd500** [comment]
I pushed changes of trying using clang on the branch try-clang. It works fine on my place.
Please try it and let me know if it is OK to push to master

**Comment by mcd500** [comment]
Works with clang.
https://github.com/columbia-irt/rtptools/pull/36
