### ISSUE TITLE
make distclean

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#39]
`make distclean` should remove `autom4te.cache` and possibly other autoconf cruft.

**Comment by mcd500** [comment]
The portion in Makefile for `make distclean` are generated by autotools, so I do not see as a problem, it is limitation of autotools.
It is possible to add workaround in Makefile.am. Please refer `clean-local` in Makefile.am. 
Would be nice to have a pull requst :)

**Comment by mcd500** [comment]
Fixed.
https://github.com/columbia-irt/rtptools/commit/75c0c971c5f0c934d11314650c4592ae7f580f54
