### ISSUE TITLE
win/*.suo

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#41]
The `win/*.suo` files seem to be some binary artifacts of the windows build.
Can we remove them from the repository?

**Comment by mcd500** [comment]
Not sure, let me try it when I have time. The question type comments more suite on commenting on commits when they are added, unless you are completely sure it is the problem  :)

**Comment by mcd500** [comment]
I tried it without the *.sou file and built fine.
https://github.com/columbia-irt/rtptools/commit/f156e822bf28e229048d22d94512b35b2d320a61

**Comment by janstary** [comment]
Thanks! Please try the same with _all_ the other windows files
and please remove _everything_ that can be removed.
