### ISSUE TITLE
Get rtptools added to Homebrew

### ISSUE THREAD

**Issue by njh** [columbia-irt/rtptools#47]
It would be really useful to have rtptools available in [Homebrew](https://brew.sh/) - Open Source package manager for Mac OS.

I have created a Pull Request to get version 1.21 added here:
https://github.com/Homebrew/homebrew-core/pull/25533

**Comment by janstary** [comment]
Now that 1.22 is out, I will prepare a package in MacPorts.
(But maybe it's a good opportunity to also try Homebrew now :-)

**Comment by janstary** [comment]
https://github.com/macports/macports-ports/pull/1473

**Comment by njh** [comment]
1.22 is now in homebrew :)

```
~ $ brew install rtptools
==> Downloading https://homebrew.bintray.com/bottles/rtptools-1.22.sierra.bottle.tar.gz
Already downloaded: /Users/humfrn01/Library/Caches/Homebrew/rtptools-1.22.sierra.bottle.tar.gz
==> Pouring rtptools-1.22.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/rtptools/1.22: 17 files, 130.4KB
```

**Comment by janstary** [comment]
Cool, imported into macports in the meantime too :-)
