### ISSUE TITLE
Move source files to 'src'?

### ISSUE THREAD

**Issue by njh** [columbia-irt/rtptools#48]
Hi,

It is a bit daunting when you first look at the repository due to the number of files in root.

Might be a bit tidier if the source files were moved to a 'src' directory?

nick.

**Comment by janstary** [comment]
Please don't - it's a needless complication. Having everything in one dir
is the simplest way to build. No need to recognize some SRCDIR ar whether
tha manoage is one `../man/` above or anything like that. Keep it simple.

**Comment by njh** [comment]
For me simple is putting the source files in a src directory, but we can agree to disagree.

**Comment by mcd500** [comment]
I saw this comment and did not know it was already closed.
Many project starting to have `src` `doc` `test` directories and the builds will be stored under `build`.
We might come back on this topic if rtptools start to have more files and stating to cleanup in the feature.
