### ISSUE TITLE
Configure file is in transition.

### ISSUE THREAD

**Issue by mcd500** [columbia-irt/rtptools#58]
I have merged the new configure file replacing auotools.
During the transition, some of the feature of autotools is missing but we are planning to add features one by one.
I know there are people who do not like having less features but it is indispensable during of any project when refactoring. I will take full responsible of this situation and please do not flame @janstary.

The features not working at the moment where I noticed are:
*) make rprm
*) make check (honestly there were no test program on rtptools)
*) cross-compilation
*) building on Windows.

I have created a branch which is based on autotool as `with-autotools`.
For those who are just interested on using rtptools with the feature above, 
$ git clone https://github.com/columbia-irt/rtptools rtptools-autotools
$ cd rtptools-autotools
$ git checkout with-autotools
$ aclocal
$ automake --add-missing --force-missing
$ autoconf

I have no plan to update the branch with-autotools when the master evolves.
The branch with-autotools will be frozen and it is planned to be deleted when the master become mature.

**Comment by janstary** [comment]
Nothing has changed regarding Windows - what exactly is the breakage?
(In general, please open a specific issue for each specific problem.)

**Comment by janstary** [comment]
* `make rpm` has its own https://github.com/columbia-irt/rtptools/pull/60 and https://github.com/columbia-irt/rtptools/issues/83
* `make check` has nothing to do with the `./configure` script
* building on windows works fine, and has nothing to do with `./configure`
* cross-compilation has its own https://github.com/columbia-irt/rtptools/issues/59

I believe we can close this generic issue.
Generaly, open specific tickets for specific problems.

**Comment by janstary** [comment]
Can we close this now?

**Comment by mcd500** [comment]
This is definitely obsolete content. Closing it.
