### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by mcd500** [columbia-irt/rtptools#69]
After merging the 
https://github.com/columbia-irt/rtptools/pull/64
for fixing distcheck and cleaning up the package of rtptools.
it fails to build on Windows.

Probably adding 
#include <stding.h>
on both rtp.h and rtpdump.h
and 
adding ENTRY which was declared in ansi.h will fix it.

This is some of the error messages:
3>d:\documents\dev\rtptools\rtptools-win\rtpdump.h(59): error C2061: syntax error : identifier 'uint16_t'
3>d:\documents\dev\rtptools\rtptools-win\rtpplay.c(146): error C2065: 'ENTRY' : undeclared identifier

**Comment by mcd500** [comment]
Fixed
https://github.com/columbia-irt/rtptools/commit/b267e8c08d55ad0793c097fe3b6e49df540aed0b

End up finding that Windows do not have hsearch.

**Comment by janstary** [comment]
Thanks for checking. So it seems we still do need the bundled hsearch implementation,
because Windows does not have it.
