### ISSUE TITLE
Does not support big-endian system at the moment

### ISSUE THREAD

**Issue by mcd500** [columbia-irt/rtptools#71]
With the autotools,
the endian of the system was detected by
#AC_C_BIGENDIAN

and rtp.h was expecting to have WORDS_BIGENDIAN or not to properly work on bigendian system.
```
#ifdef WORDS_BIGENDIAN
#define RTP_BIG_ENDIAN 1
#else
#define RTP_LITTLE_ENDIAN 1
#endif
```

Something similar of AC_C_BIGENDIAN in configure would probably do.

**Comment by janstary** [comment]
Yes, I have a branch with `have-bigendian.c` that sets `RTP_BIG_ENDIAN` as used in the code.
I would like to put it on top of https://github.com/columbia-irt/rtptools/pull/72 though, where the whole infrastructure gets cleaner.

**Comment by janstary** [comment]
fixed in https://github.com/columbia-irt/rtptools/pull/81

**Comment by mcd500** [comment]
Thanks, this is one step forward for the
https://github.com/columbia-irt/rtptools/issues/59
