### ISSUE TITLE
replace hsearch()?

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#73]
Currently, `rtpplay.c` uses `hsearch(3)` to remember the SSRCs and their timstamps.
Now, `hsearch` is available almost everywhere, but does not exist on windows.

We provide a bundled implementation of hsearch (buggy, straight from glibc 2.0, 1993),
and with https://github.com/columbia-irt/rtptools/pull/72 we properly test whether to use it.

I believe that the use of a full-fledged hash table implementation is overkill for what we need,
and should replace it with a simple list. Then we could dispense with `hsearch` altogether,
wouldn't need to test for it, wouldn't need to provide a compatibility implementation,
and could do one thing uniformly on all systems.

**Comment by mcd500** [comment]
Confirmed the 
https://github.com/columbia-irt/rtptools/pull/72
works for Windows after 
https://github.com/columbia-irt/rtptools/commit/f12d68e5f9017446c6c25d54c7ec0a8c1b5d0342

**Comment by mcd500** [comment]
I was also thinking to work on replacing hsearch with a simple list after working on `make rpm`

Please let me know when you are going t work on a simple list, to save our time by preventing both of us using the duplicated time.

**Comment by janstary** [comment]
Prepared in  https://github.com/columbia-irt/rtptools/pull/89

**Comment by janstary** [comment]
Newer version in https://github.com/columbia-irt/rtptools/pull/128

**Comment by janstary** [comment]
Solved for `rtpplay` in https://github.com/columbia-irt/rtptools/pull/128.
