### ISSUE TITLE
winsock

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#75]
Windows needs to call `WSAStartup()` before using sockets,
which we do in `win/winsocklib.c` in the `startupSocket()` function
(and define it away in `sysdep.h` if not on windows).
Otherwise, we would get `socket: No error`.

In the actual `WSAStartup()`, we require version `1.1`, which according to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms742213(v=vs.85).aspx)
is the latest available for  Windows 95 and Win NT 3.51. (Yes, it's 2018 here.)
 The latest version documented there is `2.2`, which supports up to Windows Server 2008.

Can windows users please test the following?

* how much we still need to do this (`no error` does not sound like an error)
* how much we need/want to stay with version `1.1` of winsock

**Comment by janstary** [comment]
In `sysdep.h`, we include `winsock2.h`.
According to [msdn](https://msdn.microsoft.com/en-us/library/ms738566.aspx), we indeed need to do that,
and according to [wiki](https://en.wikipedia.org/wiki/Winsock), the latest version is `2.2.1`.

**Comment by mcd500** [comment]
Even the latest `2.2.1`, without calling WSAStartup() then the first call of socket() will return with error `!= 0`.
I have no idea when the MS will change this behavior on the socket().
The `socket: No error` is show from `perror()` in rtptools which will not show exact error message on Windows, since `perror()` does not mapped to Windows'ish error returns described at 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms742213(v=vs.85).aspx

**Comment by mcd500** [comment]
I have tried `2.2.1` on Win10 for this result.
I also have no idea why MS does not map error messages to `perror()` in `winsock2.h`.

**Comment by mcd500** [comment]
I think we just have to live with this behavior.

**Comment by mcd500** [comment]
Windows have equivalent of perror() for the function provided by `winsock2.h` which is WSAGetLastError().
https://msdn.microsoft.com/en-us/library/windows/desktop/ms741580(v=vs.85).aspx
However the  WSAGetLastError() only works for `winsock2.h` and not for the rest of the POSIX-like functions.
https://support.microsoft.com/en-us/help/99456/win32-equivalents-for-c-run-time-functions

This is off topic from the winsock but I do not feel it is worth selectively using WSAGetLastError() and perror() only for Windows.

**Comment by janstary** [comment]
Thanks for checking. So it seems we still need to to this. Does anyone know if it is
in any sense better to require the `2.2` WSA as opposed to the `1.1` we currently ask for?

(As for the error messages, I plan to replace the `perror()` messages with `err()`,
exiting where appropriate. For example here: if we cannot open a socket,
we should fail hard and immediately, because what else can we do wihout a sock?)

**Comment by mcd500** [comment]
`2.2` was working fine and committed.
https://github.com/columbia-irt/rtptools/commit/13b11f1f48d1e3077d4ada610092eafb72fcb296
Thank you for pointing it out. I forgot to commit it when I was doing try and error of this thread.

Also the `err()` is the definitely the way to go instead of `perror()`

**Comment by janstary** [comment]
Thanks.
