### ISSUE TITLE
config.h is not included with make dist, failes to build on Windows

### ISSUE THREAD

**Issue by mcd500** [columbia-irt/rtptools#78]
1>d:\users\public\dev\rtptools-1.23\rtptrans.c(46): fatal error C1083: Cannot open include file: 'config.h': No such file or directory

**Comment by janstary** [comment]
fixed in https://github.com/columbia-irt/rtptools/pull/82

**Comment by janstary** [comment]
`config.h` is a product of `./configure`, specific to the given system,
so it makes no sense to include it in `dist`.

But on windows, `rtptrans.c` does not need to include `config.h` at all;
we know it does not even have `sendmsg()`.
