### ISSUE TITLE
make depend fails, CentOS, Fedora do not have mkdep

### ISSUE THREAD

**Issue by mcd500** [columbia-irt/rtptools#79]
For some reason, rpm based Linux do not have `mkdep`.
Ubuntu has `mkdep`

**Comment by janstary** [comment]
The latest releases of MacOS also don't have `mkdep`.

If the system does not have `mkdep`, you cannot run `make depend`
(much like you can't run `make all` if you don't have a compiler).

That's it. There is nothing to "fix" about it in rtptools. We can close this.

Note that `make depend` is very rarely needed, if ever again.
I have used it once: when preparing the original `Makefile.depend`.
The list of source files is short and known in advance, and their relations
described in `Makefile.depend` never change. Indeed, the only edits
to `Makefile.depend` is the gradual addition of the obvious
`compat-foo.o: compat-foo.c`, trivially added manualy.

**Comment by mcd500** [comment]
Thanks for the details.
For the rpm based Linux and MacOS, who would be changing the code, editing Makefile.depend manually is fine.
Debian/Ubunto has mkdep.
