### ISSUE TITLE
RFC: moving getopt() to compat-*

### ISSUE THREAD

**Issue by mcd500** [columbia-irt/rtptools#84]
This is just for request for comment. Not an issue.

Just Windows did not have getopt() when in the era of rtptools was working with autotools, the getopt.h/c are stored under directory win.

Since we are starting using compat-*, would be good to move getopt.h/c gettimeofday.h/c to compat-*?

The gettimeofday.c uses windows dedicated functions and do not work other than Win but  the code of getopt.h/c is universal from 
https://github.com/kimgr/getopt_port

**Comment by janstary** [comment]
On windows, you cannot even run the `./configure` script (not this one, not the autoconf one).
The windows build is separate from the rest of the build system: it does not use it. For systems
other than windows, there is no need for a `compat` implementation of `getopt`.

So I would say no: leave the win specific stuff to be used by win,
don't mix it with the rest of the build system.

**Comment by janstary** [comment]
Basicaly, windows has its own separate build system,
described in the `win/*.vcxproj` files.

**Comment by janstary** [comment]
Hm, come to think of it, after https://github.com/columbia-irt/rtptools/pull/112 goes in,
having `compat-getopt.c` and `have-getopt.c` along with the others is probably the
right thing to do. I will look into it once https://github.com/columbia-irt/rtptools/pull/112 is resolved.

**Comment by janstary** [comment]
https://github.com/columbia-irt/rtptools/pull/116

**Comment by mcd500** [comment]
Thanks @janstary
