### ISSUE TITLE
rtptrans: uses ipv4 address for SSRC in RTP header

### ISSUE THREAD

**Issue by mcd500** [columbia-irt/rtptools#85]
In the rtptrans.c
```
 rtp_hdr_send.ssrc = sin_from.sin_addr.s_addr;
```

The size of ssrc and ipv4 address is same uint32_t and it is working at the moment.
The descriotion in RFC for SSRC, 
https://tools.ietf.org/html/rfc3550#page-59
```
   The SSRC identifier carried in the RTP header and in various fields
   of RTCP packets is a random 32-bit number that is required to be
   globally unique within an RTP session.  It is crucial that the number
   be chosen with care in order that participants on the same network or
   starting at the same time are not likely to choose the same number.

   It is not sufficient to use the local network address (such as an
   IPv4 address) for the identifier because the address may not be
   unique.  Since RTP translators and mixers enable interoperation among
   multiple networks with different address spaces, the allocation
   patterns for addresses within two spaces might result in a much
   higher rate of collision than would occur with random allocation.

   Multiple sources running on one host would also conflict.
```

Replace the SSRC with random generator and testing the rtptrans should be fine.
The description of generating SSRC in RFC is also described at `A.6` in
https://tools.ietf.org/html/rfc3550#page-85
The method in the RFC used md5 function which does not have in Windows and also md5 is starting to be deprecated on most of the system, might be OK to just use regular random() or own random generator.

**Comment by janstary** [comment]
The linked random generation cannot but remind me of https://www.tedunangst.com/flak/post/random-in-the-wild again. But we don't need _strong_ randomness, as in
cryptographically strong. A simple `random()` should be enough for this, right?

https://github.com/columbia-irt/rtptools/pull/90
