### ISSUE TITLE
use even-numbered ports for RTP

### ISSUE THREAD

**Issue by janstary** [columbia-irt/rtptools#93]
RFC 3550:              
   RTP relies on the underlying protocol(s) to provide demultiplexing of        
   RTP data and RTCP control streams.  For UDP and similar protocols,           
   RTP SHOULD use an even destination port number and the corresponding         
   RTCP stream SHOULD use the next higher (odd) destination port number.

**Comment by mcd500** [comment]
@janstary is this comment for adding description to the man page and usage in the future?
I just wanted to know your intention of logging this comment, since historically rtptools did not allow odd numbers for RTP ports to comply with RFC 3550.

**Comment by janstary** [comment]
Documented in https://github.com/columbia-irt/rtptools/pull/99
